In [0]:
import numpy as np
from numpy import inf

#Defining Distance between the nodes
distance = np.array([[np.inf,10,12,11,14],
                    [10,np.inf,13,15,8],
                    [12,13,np.inf,9,14],
                    [11,15,9,np.inf,16],
                    [14,8,14,16,np.inf]])

num_iterations = 100  # Number of Iterations
num_ants = 6          # Number of ants
num_cities = 5        # Number of Cities

evap_fact = 0.2       # Evaporation Factor
alpha = 1             # Pheromone Factor
beta = 2              # Visibility Factor

# Calculating the visibility of the next city
visibility = 1/distance

#Initializing the pheromone present at paths
pheromone = 0.1*np.ones((num_ants,num_cities))

#Initilizing route of ants which START and END at same city
route = np.ones((num_ants, num_cities+1),int)


#### Optimizing the Tour
for iteration in range(num_iterations):
    print("Iteration : ", iteration+1)
    
    for i in range(num_ants):
        
        #Making the copy of visibility matrix
        temp_visibility = np.copy(visibility)
        
        for j in range(num_cities - 1):
            
            # Gives the current location of the ant
            current_loc = route[i,j] - 1 
            
            # Marking the visited city as Zero
            temp_visibility[:,current_loc] = 0 
            
            # Ant makes decision on what city to go using this decision_feature
            decision_feature = pheromone[current_loc,:] ** alpha * (temp_visibility[current_loc, :] ** beta)
            
            total = np.sum(decision_feature)
            
            # Probabaility of going to next city
            prob = decision_feature / total
            
            # Calculating Cumulative probability
            cum_prob = np.cumsum(prob)
            
            # Generating random number in [0,1)
            r = np.random.random_sample()
            
            # Finding the city having probability higher then random(r)
            city = np.nonzero(cum_prob>r)[0][0]+1 
            route[i,j+1] = city # Adding that city to route
        
        # Adding Untravarsed city to the route
        left_city = list(set([i for i in range(1,num_cities+1)])-set(route[i,:-2]))[0]
        route[i,-2] = left_city
        
        
    # Making the route as optimal route
    optimal_route = np.array(route)
    print("Optiaml Route : ")
    print(optimal_route)
    
    
    #Initializing the cost of the tour for each ant
    dist_cost = np.zeros((num_ants,1),int)
    
    
#### Computation of Total Cost    
    for i in range(num_ants):
        
        sum = 0
        for j in range(num_cities-1):
            
            # Calulating the total distance travelled by each ant
            sum += distance[optimal_route[i,j]-1][optimal_route[i,j+1]-1]
        
        dist_cost[i] = sum
        print("Total Distance Travelled By Ant",i+1," : ",dist_cost[i])
    
    # Finding the index of minimum distance
    dist_min_loc = np.argmin(dist_cost)
    
    # Finding the Minimum Distance
    dist_min_cost = dist_cost[dist_min_loc]
    print("Minimum of Total Distances : ",dist_min_cost)
    
    # Finding the the route which has minimum distance 
    best_route = optimal_route[dist_min_loc,:]
    print()
    print("Best Route after Iteration",iteration + 1, ":", best_route)
    
##### Pheromone Updation   
    for i in range(num_ants):
        for j in range(num_cities-1):
            
            # Updating Pheromone by d which is low when total distance is high
            # and high when total distance is low
            d = 1 / dist_cost[i]
            pheromone[optimal_route[i,j]-1 , optimal_route[i,j+1]-1] += d
    
#### Pheromone Evaporation
    pheromone = (1 - evap_fact) * pheromone
    print("\n")


print("Best Route of all Ants :",best_route)
print()
cost_of_best_path = dist_min_cost + distance[best_route[-2]-1,0]
print("Cost of Best path : ", int(cost_of_best_path))


Iteration :  1
Optiaml Route : 
[[1 2 4 3 5 1]
 [1 4 5 2 3 1]
 [1 2 4 5 3 1]
 [1 5 2 3 4 1]
 [1 4 5 2 3 1]
 [1 2 5 4 3 1]]
Total Distance Travelled By Ant 1  :  [48]
Total Distance Travelled By Ant 2  :  [48]
Total Distance Travelled By Ant 3  :  [55]
Total Distance Travelled By Ant 4  :  [44]
Total Distance Travelled By Ant 5  :  [48]
Total Distance Travelled By Ant 6  :  [43]
Minimum of Total Distances :  [43]

Best Route after Iteration 1 : [1 2 5 4 3 1]


Iteration :  2
Optiaml Route : 
[[1 4 3 2 5 1]
 [1 2 5 4 3 1]
 [1 4 2 3 5 1]
 [1 4 3 2 5 1]
 [1 2 3 4 5 1]
 [1 2 5 4 3 1]]
Total Distance Travelled By Ant 1  :  [41]
Total Distance Travelled By Ant 2  :  [43]
Total Distance Travelled By Ant 3  :  [53]
Total Distance Travelled By Ant 4  :  [41]
Total Distance Travelled By Ant 5  :  [48]
Total Distance Travelled By Ant 6  :  [43]
Minimum of Total Distances :  [41]

Best Route after Iteration 2 : [1 4 3 2 5 1]


Iteration :  3
Optiaml Route : 
[[1 5 2 4 3 1]
 [1 3 5 4 2 1]
 [1 2 4 3 

Total Distance Travelled By Ant 4  :  [42]
Total Distance Travelled By Ant 5  :  [42]
Total Distance Travelled By Ant 6  :  [44]
Minimum of Total Distances :  [42]

Best Route after Iteration 18 : [1 4 3 5 2 1]


Iteration :  19
Optiaml Route : 
[[1 4 3 5 2 1]
 [1 4 3 5 2 1]
 [1 2 5 3 4 1]
 [1 4 3 5 2 1]
 [1 2 5 4 3 1]
 [1 3 5 2 4 1]]
Total Distance Travelled By Ant 1  :  [42]
Total Distance Travelled By Ant 2  :  [42]
Total Distance Travelled By Ant 3  :  [41]
Total Distance Travelled By Ant 4  :  [42]
Total Distance Travelled By Ant 5  :  [43]
Total Distance Travelled By Ant 6  :  [49]
Minimum of Total Distances :  [41]

Best Route after Iteration 19 : [1 2 5 3 4 1]


Iteration :  20
Optiaml Route : 
[[1 2 5 4 3 1]
 [1 3 4 2 5 1]
 [1 2 5 4 3 1]
 [1 4 3 5 2 1]
 [1 2 5 4 3 1]
 [1 4 3 5 2 1]]
Total Distance Travelled By Ant 1  :  [43]
Total Distance Travelled By Ant 2  :  [44]
Total Distance Travelled By Ant 3  :  [43]
Total Distance Travelled By Ant 4  :  [42]
Total Distance Travelled 

Total Distance Travelled By Ant 1  :  [42]
Total Distance Travelled By Ant 2  :  [42]
Total Distance Travelled By Ant 3  :  [41]
Total Distance Travelled By Ant 4  :  [41]
Total Distance Travelled By Ant 5  :  [41]
Total Distance Travelled By Ant 6  :  [41]
Minimum of Total Distances :  [41]

Best Route after Iteration 39 : [1 2 5 3 4 1]


Iteration :  40
Optiaml Route : 
[[1 2 5 3 4 1]
 [1 2 5 4 3 1]
 [1 2 5 3 4 1]
 [1 2 5 3 4 1]
 [1 2 5 3 4 1]
 [1 2 5 3 4 1]]
Total Distance Travelled By Ant 1  :  [41]
Total Distance Travelled By Ant 2  :  [43]
Total Distance Travelled By Ant 3  :  [41]
Total Distance Travelled By Ant 4  :  [41]
Total Distance Travelled By Ant 5  :  [41]
Total Distance Travelled By Ant 6  :  [41]
Minimum of Total Distances :  [41]

Best Route after Iteration 40 : [1 2 5 3 4 1]


Iteration :  41
Optiaml Route : 
[[1 2 5 3 4 1]
 [1 2 5 3 4 1]
 [1 2 5 3 4 1]
 [1 2 5 3 4 1]
 [1 2 5 4 3 1]
 [1 2 5 3 4 1]]
Total Distance Travelled By Ant 1  :  [41]
Total Distance Travelled 

Total Distance Travelled By Ant 5  :  [41]
Total Distance Travelled By Ant 6  :  [41]
Minimum of Total Distances :  [41]

Best Route after Iteration 64 : [1 2 5 3 4 1]


Iteration :  65
Optiaml Route : 
[[1 2 5 4 3 1]
 [1 2 5 3 4 1]
 [1 2 5 3 4 1]
 [1 2 5 3 4 1]
 [1 2 5 3 4 1]
 [1 2 5 3 4 1]]
Total Distance Travelled By Ant 1  :  [43]
Total Distance Travelled By Ant 2  :  [41]
Total Distance Travelled By Ant 3  :  [41]
Total Distance Travelled By Ant 4  :  [41]
Total Distance Travelled By Ant 5  :  [41]
Total Distance Travelled By Ant 6  :  [41]
Minimum of Total Distances :  [41]

Best Route after Iteration 65 : [1 2 5 3 4 1]


Iteration :  66
Optiaml Route : 
[[1 2 5 3 4 1]
 [1 2 5 3 4 1]
 [1 2 5 3 4 1]
 [1 2 5 3 4 1]
 [1 2 5 3 4 1]
 [1 2 5 3 4 1]]
Total Distance Travelled By Ant 1  :  [41]
Total Distance Travelled By Ant 2  :  [41]
Total Distance Travelled By Ant 3  :  [41]
Total Distance Travelled By Ant 4  :  [41]
Total Distance Travelled By Ant 5  :  [41]
Total Distance Travelled 

Total Distance Travelled By Ant 4  :  [41]
Total Distance Travelled By Ant 5  :  [41]
Total Distance Travelled By Ant 6  :  [41]
Minimum of Total Distances :  [41]

Best Route after Iteration 83 : [1 2 5 3 4 1]


Iteration :  84
Optiaml Route : 
[[1 2 5 3 4 1]
 [1 2 5 3 4 1]
 [1 2 5 3 4 1]
 [1 2 5 3 4 1]
 [1 2 5 3 4 1]
 [1 2 5 3 4 1]]
Total Distance Travelled By Ant 1  :  [41]
Total Distance Travelled By Ant 2  :  [41]
Total Distance Travelled By Ant 3  :  [41]
Total Distance Travelled By Ant 4  :  [41]
Total Distance Travelled By Ant 5  :  [41]
Total Distance Travelled By Ant 6  :  [41]
Minimum of Total Distances :  [41]

Best Route after Iteration 84 : [1 2 5 3 4 1]


Iteration :  85
Optiaml Route : 
[[1 2 5 3 4 1]
 [1 2 5 3 4 1]
 [1 2 5 3 4 1]
 [1 2 5 3 4 1]
 [1 2 5 3 4 1]
 [1 2 5 3 4 1]]
Total Distance Travelled By Ant 1  :  [41]
Total Distance Travelled By Ant 2  :  [41]
Total Distance Travelled By Ant 3  :  [41]
Total Distance Travelled By Ant 4  :  [41]
Total Distance Travelled 